import { Product } from "@/lib/types";

export const initialProducts: Product[] = [
  {
    id: 1,
    name: "Rice",
    quantity: 12,
    unit: "Bags",
    buyingPrice: 5080,
    sellingPrice: 6400,
    lowStock: 3,
    barcode: "",
  },
  {
    id: 2,
    name: "Beans",
    quantity: 5,
    unit: "Bags",
    buyingPrice: 2680,
    sellingPrice: 5040,
    lowStock: 3,
    barcode: "",
  },
  {
    id: 3,
    name: "Kapenta",
    quantity: 2,
    unit: "Bags",
    buyingPrice: 5200,
    sellingPrice: 6300,
    lowStock: 3,
    barcode: "",
  },
  {
    id: 4,
    name: "Eggs",
    quantity: 200,
    unit: "Trays",
    buyingPrice: 66,
    sellingPrice: 75,
    lowStock: 10,
    barcode: "",
  },
  {
    id: 5,
    name: "Wheat",
    quantity: 5,
    unit: "Bags",
    buyingPrice: 2680,
    sellingPrice: 5040,
    lowStock: 3,
    barcode: "",
  },
  {
    id: 6,
    name: "Popcorn",
    quantity: 5,
    unit: "Bags",
    buyingPrice: 2680,
    sellingPrice: 5040,
    lowStock: 3,
    barcode: "",
  },
];